name: Android CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches: [ "master" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set version variables
      id: set_version
      run: |
        if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
          VERSION_NAME=$(echo ${GITHUB_REF#refs/tags/} | sed 's/^v//')
        else
          VERSION_NAME=${{ secrets.VERSION_NAME }}
        fi
          
        VERSION_CODE=$((${{ secrets.VERSION_CODE }} + 1))
          
        echo "VERSION_CODE=$VERSION_CODE" >> $GITHUB_ENV
        echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Assemble Debug build
      run: ./gradlew assembleDebug

    - name: Run Unit Test
      run: ./gradlew testDebugUnitTest

    - name: build release
      run: ./gradlew assembleRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_KEYSTORE_PASSWORD: ${{ secrets.SIGNING_KEYSTORE_PASSWORD }}

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk

    - name: upload artifact to Firebase App Distribution
      uses: wzieba/Firebase-Distribution-Github-Action@v1
      with:
        appId: ${{secrets.FIREBASE_APP_ID}}
        serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
        groups: testers
        file: app/build/outputs/apk/release/app-release.apk
